# Generated by Django 5.1.4 on 2025-04-22 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_rename_timestamp_payment_payment_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
